In [44]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [45]:
data = pd.read_csv("Churn_Modelling.csv")

data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [46]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [47]:
pd.DataFrame(x)

0        1       2   3   4          5  6  7  8          9
0     619   France  Female  42   2        0.0  1  1  1  101348.88
1     608    Spain  Female  41   1   83807.86  1  0  1  112542.58
2     502   France  Female  42   8   159660.8  3  1  0  113931.57
3     699   France  Female  39   1        0.0  2  0  0   93826.63
4     850    Spain  Female  43   2  125510.82  1  1  1    79084.1
...   ...      ...     ...  ..  ..        ... .. .. ..        ...
9995  771   France    Male  39   5        0.0  2  1  0   96270.64
9996  516   France    Male  35  10   57369.61  1  1  1  101699.77
9997  709   France  Female  36   7        0.0  1  0  1   42085.58
9998  772  Germany    Male  42   3   75075.31  2  1  0   92888.52
9999  792   France  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')


In [6]:
x=np.array(ct.fit_transform(x))


In [7]:
rough = pd.DataFrame(x)

In [8]:
rough

0    1    2    3       4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  Female  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  Female  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  Female  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  Female  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  Female  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ...     ...  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771    Male  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516    Male  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  Female  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772    Male  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 4]=le.fit_transform(x[:,4])

In [10]:
rough = pd.DataFrame(x)
rough

0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

**feture scaling is must for artificial neural networks**

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

***building a ann***

**initialising ann**

In [13]:
ann= tf.keras.models.Sequential()

**adding first fully connected hidden layer**

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**adding second fully connected hidden layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**adding output layer**

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**compiling the ann**

In [24]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

**training the ann**

In [25]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
235/235 [==============================] - 3s 4ms/step - loss: 0.6080 - accuracy: 0.7301
Epoch 2/100
235/235 [==============================] - 1s 5ms/step - loss: 0.4929 - accuracy: 0.7963
Epoch 3/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4617 - accuracy: 0.7960
Epoch 4/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4479 - accuracy: 0.7973
Epoch 5/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4405 - accuracy: 0.8017
Epoch 6/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4360 - accuracy: 0.8067
Epoch 7/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4323 - accuracy: 0.8083
Epoch 8/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4292 - accuracy: 0.8113
Epoch 9/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4269 - accuracy: 0.8119
Epoch 10/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4245 - accura

235/235 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8651
Epoch 82/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8660
Epoch 83/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3293 - accuracy: 0.8641
Epoch 84/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3291 - accuracy: 0.8655
Epoch 85/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3289 - accuracy: 0.8656
Epoch 86/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3290 - accuracy: 0.8652
Epoch 87/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3288 - accuracy: 0.8643
Epoch 88/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3289 - accuracy: 0.8652
Epoch 89/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3285 - accuracy: 0.8663
Epoch 90/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3286 - accuracy: 

In [26]:
y_predict = ann.predict(x_test)

79/79 [==============================] - 1s 3ms/step


In [27]:
np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1)

array([[0.27376097, 0.        ],
       [0.25354275, 1.        ],
       [0.1128312 , 0.        ],
       ...,
       [0.21099664, 0.        ],
       [0.09667739, 0.        ],
       [0.05423186, 0.        ]])

In [63]:

y_predict_binary[y_predict<0.5]=0
y_predict_binary[y_predict>=0.5]=1

TypeError: only integer scalar arrays can be converted to a scalar index

In [31]:
y_predict

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [32]:
pd.DataFrame(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

0    1
0     0.0  0.0
1     0.0  1.0
2     0.0  0.0
3     0.0  0.0
4     0.0  0.0
...   ...  ...
2495  0.0  0.0
2496  1.0  0.0
2497  0.0  0.0
2498  0.0  0.0
2499  0.0  0.0

[2500 rows x 2 columns]

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_predict, y_test)

array([[1918,  263],
       [  73,  246]], dtype=int64)

In [34]:
    accuracy_score(y_predict, y_test)

0.8656

**prediction for a single observation**

geography : france
credit score : 600
gender : male
age : 40
tenure : 3yrs
balance : 60,000
no of products : 2
have a credit card : yes
is an active member : yes
estimated salary 50,000
is it over ?

In [54]:
x_pred =[600, 'France', 'Male', 40, 3, 60000, 2,1,1, 50000 ]

In [55]:
x_pred=np.array(ct.fit_transform([x_pred]))

In [56]:
x_pred

array([[1.0, 600, 'Male', 40, 3, 60000, 2, 1, 1, 50000]], dtype=object)

In [52]:
x_pred[:, 2]=le.fit_transform([x_pred[:,2]])

C:\Users\dheer\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [53]:
x_pred

array([[1.0, 600, 0, 40, 0, 60000, 2, 1, 1, 50000]], dtype=object)

In [58]:
x_pred_jugaad=[1.0, 0.0,0.0, 600, 1, 40, 3, 60000,2,1,1,50000]

In [68]:
ann.predict(sc.transform([x_pred_jugaad]))

1/1 [==============================] - 0s 50ms/step


array([[0.03981573]], dtype=float32)

In [61]:
one_pred

array([[1.]], dtype=float32)